# Reports subdirectory configuration
# Inherits from parent site configuration

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

# Use parent site's layouts
layouts_dir: ../_layouts

# Use parent site's includes
includes_dir: ../_includes

# Use parent site's sass
sass:
  sass_dir: ../_sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-include-cache

# Markdown
markdown: kramdown
highlighter: rouge

# Site info
title: Reports
description: Reports and analysis archive
url: https://www.aledlie.com
baseurl: /reports

# Author
author:
  name: Alyshia Ledlie
  avatar: /images/profile.jpg
  bio: I write code, make aggressively mediocre jokes, and scale companies.
